name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.18.0

    - name: Build
      run: |
        mvn install
        mv target/macro-mermaid-${{ github.ref_name }}.xar ./

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: macro-mermaid-${{ github.ref_name }}.xar
